pool:
  name: Azure Pipelines
  vmImage: 'vs2017-win2016'
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 2.x'
  inputs:
    versionSpec: 2.x

- script: 'dir'
  displayName: 'Seeing DIR'

- script: 'pip install -r Application/requirements.txt'
  displayName: 'Install dependencies'

- script: 'pip install pytest && pytest Tests/unit_tests --junitxml=test-results.xml && pip install pycmd && py.cleanup Tests/' 
  'dir'
  'cd'
  displayName: pytest

- task: PublishTestResults@2
  displayName: 'Publish Test Results test-results.xml'
  inputs:
    testResultsFiles: 'test-results.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'Python Unit tests'

- script: 'dir'
  'cd'
  displayName: 'Seeing DIR'

- task: ArchiveFiles@2
  displayName: 'Archive application'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Application'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/Application.zip'

- script: 'dir'
  'cd'
  displayName: 'Seeing DIR'

- task: ArchiveFiles@2
  displayName: 'Archive Tests'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Tests'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/Tests.zip'

- script: 'dir'
  'cd'
  displayName: 'Seeing DIR'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

    

